name: CI

# on: [push, pull_request]
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main


jobs:
  build-jdk11:
    runs-on: ubuntu-latest
    name: Build project with Java 11
    steps:
    - name: 'Checkout Repo'
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Build with Maven
      run: mvn clean compile install package
  