name: CI

# on: [push, pull_request]
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Bump Version and Commit"]
    types:
      - completed


jobs:
  build-jdk11:
    runs-on: ubuntu-latest
    name: Build project with Java 11
    steps:
    - name: 'Checkout Repo'
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 11
        cache: maven

    - name: Build with Maven
      run: mvn clean compile install package

    - name: Create Staging dir
      run: mkdir staging && cp target/*.jar staging

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: staging

    - name: Build Docker image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: calculator-testing
        image_tag: 0.0.1
        push_image_and_stages: false

  
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: 'Test with Maven'
        run: mvn -B test --file pom.xml

  increment-version:
    name: Increment version
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4

      - name: Increment version
        id: bump-version
        uses: ./.github/workflows/actions/custom_action
        with:
          version-file-path: 'VERSION'
          version-type: 'minor'

      - name: Use the new version
        run: echo "New version is ${{ steps.bump-version.outputs.new-version }}"

      - name: Commit changes
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_MAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config --global user.email "${GIT_USER_EMAIL}"
          git config --global user.name "${GIT_USER_NAME}"
          git add VERSION
          git commit -m "Bump version to ${{ steps.bump-version.outputs.new-version }}"
          git push
